services:
  cool-compiler:
    build:
      context: .
      target: dev-envs
    tty: true
    container_name: cs143-compiler
    volumes:
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
      - type: bind
        source: "./class"
        target: "/usr/class"