services:
  cool-compiler:
    # build:
    #   context: .
    #   target: dev-envs
    image: i386/gcc
    tty: true
    container_name: cs143-compiler
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./class:/usr/class"